# Population user passwords — generated ONCE at lab creation, versioned
# with the lab. deploy.sh never regenerates these.
{
  "pf_pop_secrets": {
    "Jack_Bootstrap": "jOVP@KGm5jlaf-GS4xJ2",
    "Philip_Dalma": "t=0!mye%9BQ172_CoABJ",
    "James_Dalma": "5XOdt$nAHE8QLp@_f65G",
    "Teague_Smyth": "&mCZJkkXSzx1!_flYZJT",
    "Scarlett_Ketwig": "QN!YNoFj0rQYzkTJA1Ra",
    "Anamaria_Bootstrap": "S##_hj&yv$DZEr2dKsBE",
    "Salazar_Feng": "&TMV0cmZNTS#GeGQAEiK",
    "Blackbeard_Teague": "7YlTN9^X9^mgzt!pHyZ3",
    "Blackbeard_Turner": "sWak*D9RnW9Ob#$6sOiN",
    "Tia_Blackbeard": "e-WGjKuX%wk=-9Hkeq0A",
    "Will_Norrington": "F^juR5QuXlhaQ_db62zl",
    "Scarlett_Blackbeard": "orSSZ&41LHwJd^niGWMR",
    "Davy_Bootstrap": "QA-%7q8U3L7a3LN^Rv*-",
    "Angelica_Teague": "hYHrkL0xViY%&dZrjE57",
    "Elizabeth_Feng": "grKhfOT@Kc2WtA6_y%05",
    "Anamaria_Beckett": "DPWE8k05_lprt0fGo6c3",
    "Tia_Barbossa": "@uc31B$feTlM%yeJarKH",
    "Scarlett_Blackbeard2": "f8ote*afIfIiajl&WajX",
    "James_Barbossa": "C0X&fttSdxuS7M223V#9",
    "Elizabeth_Sparrow": "$D9e^c7OMm4NE-L&xbRf",
    "Salazar_Ketwig": "dDoKf3NVa4!Ub5CCUYhS",
    "James_Jones": "WqHEV2q8nuUe_un1jQdQ"
  }
}
