# PurpleForge — thin Azure Terraform layer.
# Reuses the resource shapes proven by vendor/GOAD/template/provider/azure/*.tf
# (azurerm_windows_virtual_machine + CustomScriptExtension WinRM bootstrap,
# azurerm_linux_virtual_machine for the bastion) but rewrites network.tf from
# scratch: GOAD's own Azure template ships no NSG at all and gives the jumpbox
# an SSH-open-to-the-world public IP, which violates PurpleForge's isolation
# invariant (CLAUDE.md #1). Values are supplied via terraform.tfvars.json,
# generated by scripts/forge.py from lab-manifest.json — these .tf files stay
# plain, valid HCL (no string templating) so `terraform validate`/`plan` catch
# real mistakes.
terraform {
  required_version = ">= 1.5.0"
  required_providers {
    azurerm = {
      source  = "hashicorp/azurerm"
      version = "~> 3.116"
    }
    tls = {
      source  = "hashicorp/tls"
      version = "~> 4.0"
    }
  }

  # CLAUDE.md invariant #4: state lives in a remote backend with locking,
  # never local. Partial config on purpose — the actual storage
  # account/container/key are lab-specific and supplied at init time:
  #   terraform init -backend-config=backend.hcl
  # scripts/forge.py generate writes backend.hcl next to this file from
  # lab.name (see .claude/skills/infra-azure/SKILL.md for the one-time
  # bootstrap: the storage account holding state has to exist before any
  # lab's own `terraform init` can point at it — it is not itself managed by
  # this module, the classic chicken-and-egg of remote state).
  backend "azurerm" {}
}

provider "azurerm" {
  features {}
}
