# PurpleForge — thin AWS Terraform layer.
# The on-prem/cloud sibling of templates/terraform/azure/*.tf. It reuses the
# SAME resource shapes PurpleForge already proves on Azure — a WireGuard
# bastion as the only routable host, private-IP-only Windows VMs, a WinRM
# bootstrap via the instance's user_data (the AWS analogue of Azure's
# CustomScriptExtension), deny-by-default security groups, and a remote,
# locked state backend — just expressed in AWS primitives. There is no
# resource-group equivalent in AWS, so every resource is scoped by name
# prefix (var.lab_name) and tagged lab/project via the provider default_tags
# below, which is also what the auto_shutdown Lambda and the teardown
# verification filter on.
#
# Values are supplied via terraform.tfvars.json, generated by scripts/forge.py
# from lab-manifest.json — these .tf files stay plain, valid HCL (no string
# templating) so `terraform validate`/`plan` catch real mistakes.

provider "aws" {
  region = var.region

  default_tags {
    tags = {
      lab     = var.lab_name
      project = "purpleforge"
    }
  }
}
